package jun.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.EnableAspectJAutoProxy;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@SpringBootApplication
@ComponentScan("jun.demo.*")
@EnableAspectJAutoProxy
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
